name: BBQ Clinic
favicon: null
layout_spectrum: 0.1425906119402498
typography_spectrum: 0.7692794224712998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.010690740775316954
  lightness: 0.7928182312753052
  saturation: 0.47834061412140727
  rhythmicContrast: 0.5534462376963347
purpose: []
